### ISSUE TITLE
Sell rule "Low level Food" does not work

### ISSUE THREAD

**Issue by waytoomuchgaming** [typicalzergling/vendor#53]
What version of Vendor are you using?
4.1.8

Is this a WoW Classic issue or a WoW Retail issue?
Classic

What is your WoW Client language? (Vendor uses some string matching and some bugs may be due to localization)
english US

What is the issue?
Sell rule "Low level Food" does not work

Did you discover any workarounds to the issue?
I put all low level food in  "always sell" list

**Comment by typicalzergling** [comment]
This is probably because we explicitly leave level 1 food off the list. But we identified some food, particularly food that heals % based health or mana, is often set to itemlevel 1 and is usable by anyone. There is no way to discern whether the level 1 food really is useful to a max level character, or if that level 1 food is worthless.  But since you typically don't collect level 1 food unless your'e in a starting zone 1-10, we erred on the side of don't sell it on the assumption that you are more likely to encounter level 1 food that IS useful. 

If you really want to sell level 1 food, then you can create a custom rule that mimics the built in rule except it doesn't have the level 1 exemption, and then disable the built in food rule and use your custom one instead.
